_commit: 0.0.2rc-219-g781ce0c
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: true
copyright: Bartosz Sławecki
description: The Discord bot for Coherent OSS.
docs: false
email: bartoszpiotrslawecki@gmail.com
github: coherent-oss
license: MIT
package: cobot
precommit: true
pypi: false
pypy: false
python: '3.10'
python_until: ''
repo: cobot
tests: true
tidelift: false
visibility: public
wip: true
